# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genome.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'genome.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgenome.proto\x12\tgenome.v1\"\xb5\x01\n\x15GenerateGenomeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12(\n\x05tasks\x18\x02 \x03(\x0b\x32\x19.genome.v1.HistoricalTask\x12\x30\n\tschedules\x18\x03 \x03(\x0b\x32\x1d.genome.v1.HistoricalSchedule\x12/\n\x0e\x62iometric_logs\x18\x04 \x03(\x0b\x32\x17.genome.v1.BiometricLog\"\xa9\x01\n\x0eHistoricalTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x16\n\x0epriority_score\x18\x05 \x01(\x05\x12\x18\n\x10\x64uration_minutes\x18\x06 \x01(\x05\x12\x0e\n\x06\x64ue_at\x18\x07 \x01(\x03\x12\x15\n\rsaves_minutes\x18\x08 \x01(\x05\"\x89\x01\n\x12HistoricalSchedule\x12\x13\n\x0bschedule_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x03\x12\x17\n\x0f\x61llocation_type\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"\x8d\x01\n\x0c\x42iometricLog\x12\x10\n\x08log_date\x18\x01 \x01(\t\x12\x1c\n\x14sleep_duration_hours\x18\x02 \x01(\x02\x12\x1a\n\x12resting_heart_rate\x18\x03 \x01(\x05\x12\x12\n\nstep_count\x18\x04 \x01(\x05\x12\x1d\n\x15\x63omputed_energy_score\x18\x05 \x01(\x05\"\x98\x01\n\x16GenerateGenomeResponse\x12\x1b\n\x13\x64\x65\x61\x64line_risk_score\x18\x01 \x01(\x05\x12\x12\n\npeak_hours\x18\x02 \x03(\t\x12(\n\x08insights\x18\x03 \x03(\x0b\x32\x16.genome.v1.InsightCard\x12#\n\x1bscheduling_preferences_json\x18\x04 \x01(\t\"S\n\x0bInsightCard\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06impact\x18\x04 \x01(\t2f\n\rGenomeService\x12U\n\x0eGenerateGenome\x12 .genome.v1.GenerateGenomeRequest\x1a!.genome.v1.GenerateGenomeResponseB?Z=github.com/lastminutelifesaver/gateway/gen/genome/v1;genomev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genome_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/lastminutelifesaver/gateway/gen/genome/v1;genomev1'
  _globals['_GENERATEGENOMEREQUEST']._serialized_start=28
  _globals['_GENERATEGENOMEREQUEST']._serialized_end=209
  _globals['_HISTORICALTASK']._serialized_start=212
  _globals['_HISTORICALTASK']._serialized_end=381
  _globals['_HISTORICALSCHEDULE']._serialized_start=384
  _globals['_HISTORICALSCHEDULE']._serialized_end=521
  _globals['_BIOMETRICLOG']._serialized_start=524
  _globals['_BIOMETRICLOG']._serialized_end=665
  _globals['_GENERATEGENOMERESPONSE']._serialized_start=668
  _globals['_GENERATEGENOMERESPONSE']._serialized_end=820
  _globals['_INSIGHTCARD']._serialized_start=822
  _globals['_INSIGHTCARD']._serialized_end=905
  _globals['_GENOMESERVICE']._serialized_start=907
  _globals['_GENOMESERVICE']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
