# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x0cscheduler.v1\"\x9e\x01\n\x14MatchScheduleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12/\n\nbusy_slots\x18\x02 \x03(\x0b\x32\x1b.scheduler.v1.CalendarEvent\x12)\n\ttask_pool\x18\x03 \x03(\x0b\x32\x16.scheduler.v1.TaskItem\x12\x19\n\x11user_energy_score\x18\x04 \x01(\x05\"]\n\rCalendarEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\x14\n\x0cis_tentative\x18\x04 \x01(\x08\"w\n\x08TaskItem\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\"\n\x1a\x65stimated_duration_minutes\x18\x03 \x01(\x05\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x15\n\rhard_deadline\x18\x05 \x01(\x03\"`\n\x15MatchScheduleResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x36\n\x0b\x61llocations\x18\x02 \x03(\x0b\x32!.scheduler.v1.ScheduledAllocation\"\x81\x01\n\x13ScheduledAllocation\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\x17\n\x0f\x61llocation_type\x18\x04 \x01(\t\x12\x1a\n\x12\x63reate_ghost_block\x18\x05 \x01(\x08\x32l\n\x10SchedulerService\x12X\n\rMatchSchedule\x12\".scheduler.v1.MatchScheduleRequest\x1a#.scheduler.v1.MatchScheduleResponseBEZCgithub.com/lastminutelifesaver/gateway/gen/scheduler/v1;schedulerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/lastminutelifesaver/gateway/gen/scheduler/v1;schedulerv1'
  _globals['_MATCHSCHEDULEREQUEST']._serialized_start=34
  _globals['_MATCHSCHEDULEREQUEST']._serialized_end=192
  _globals['_CALENDAREVENT']._serialized_start=194
  _globals['_CALENDAREVENT']._serialized_end=287
  _globals['_TASKITEM']._serialized_start=289
  _globals['_TASKITEM']._serialized_end=408
  _globals['_MATCHSCHEDULERESPONSE']._serialized_start=410
  _globals['_MATCHSCHEDULERESPONSE']._serialized_end=506
  _globals['_SCHEDULEDALLOCATION']._serialized_start=509
  _globals['_SCHEDULEDALLOCATION']._serialized_end=638
  _globals['_SCHEDULERSERVICE']._serialized_start=640
  _globals['_SCHEDULERSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
