# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: triage.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'triage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctriage.proto\x12\ttriage.v1\"\xba\x01\n\x14ProcessTriageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x65mail_id\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x14\n\x0c\x62ody_content\x18\x05 \x01(\t\x12\x1a\n\x12received_timestamp\x18\x06 \x01(\x03\x12,\n\x0cuser_context\x18\x07 \x01(\x0b\x32\x16.triage.v1.UserContext\"W\n\x0bUserContext\x12\x14\n\x0c\x65nergy_score\x18\x01 \x01(\x05\x12\x18\n\x10\x63urrent_location\x18\x02 \x01(\t\x12\x18\n\x10\x61\x63tive_task_tags\x18\x03 \x03(\t\"\xaf\x01\n\x15ProcessTriageResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x1d\n\x15triage_priority_score\x18\x02 \x01(\x05\x12\x15\n\rurgency_level\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x04 \x01(\t\x12\x1a\n\x12\x64raft_payload_json\x18\x05 \x01(\t\x12\x1e\n\x16\x66riction_saved_minutes\x18\x06 \x01(\t2c\n\rTriageService\x12R\n\rProcessTriage\x12\x1f.triage.v1.ProcessTriageRequest\x1a .triage.v1.ProcessTriageResponseB?Z=github.com/lastminutelifesaver/gateway/gen/triage/v1;triagev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/lastminutelifesaver/gateway/gen/triage/v1;triagev1'
  _globals['_PROCESSTRIAGEREQUEST']._serialized_start=28
  _globals['_PROCESSTRIAGEREQUEST']._serialized_end=214
  _globals['_USERCONTEXT']._serialized_start=216
  _globals['_USERCONTEXT']._serialized_end=303
  _globals['_PROCESSTRIAGERESPONSE']._serialized_start=306
  _globals['_PROCESSTRIAGERESPONSE']._serialized_end=481
  _globals['_TRIAGESERVICE']._serialized_start=483
  _globals['_TRIAGESERVICE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
